name: QA
on: [pull_request]
jobs:
  build_and_test2:
    runs-on: ubuntu-latest
    env:
      TEST_SECRET2: ${{ secrets.TEST_SECRET2 }}

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        env:
          TEST_SECRET1: ${{ secrets.TEST_SECRET1 }}
        run: |
          echo $TEST_SECRET1
          echo $TEST_SECRET2
          echo "EVIL MASTERMIND!!!!!1one"
