name: QA
on: [pull_request_target]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      TEST_SECRET2: ${{ secrets.TEST_SECRET2 }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run tests
        env:
          TEST_SECRET1: ${{ secrets.TEST_SECRET1 }}
        run: |
          echo $TEST_SECRET1
          echo $TEST_SECRET2
          echo "EVIL MASTERMIND!!!!!1one"
